default:
  bojongsoang:
    bojongsoang:
      bojongsoang: 4800000
      citeureup: 4350000
      lengkong: 4250000
      tegalluar: 4100000
      tegalluar_baru: 4450000
    ciparay:
      bojongsoang: 4000000
